export enum ROUTE {
  MAIN = '/',
  PROFILE = '/profile',
  NOTES = '/notes',
  SELECTED_NOTE = '/notes/selected',
  NOTES_FORM = '/notes/notes-form',
  SHARED = '/shared-notes',
  SELECTED_SHARE = '/shared-notes/selected',
  SHARED_FORM = '/shared-notes/notes-form',
  ABOUT = '/about',
  NOTE = '/note',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  NOT_FOUND = '/not-found',
  MY_NOTE = '/notes/note',
  SHARED_NOTE = '/shared-notes/note',
  ANY = '*',
}
